### ISSUE TITLE
typo in BOM

### ISSUE THREAD

**Issue by jpnielsen** [pms67/LeDSP-Audio-SoM#1]
https://github.com/pms67/LeDSP-Audio-SoM/blob/main/hw_manufacturing/LeDSP-BOM.csv

SE5218DLG-LF-1.8V | IC REG LINEAR 3.3V 500MA SOT23-5

should be changed to 

SE5218DLG-LF-1.8V | IC REG LINEAR 1.8V 500MA SOT23-5

**Comment by pms67** [comment]
Thanks, good spot - I've updated the BOM.
